# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   ╔╦╗╦═╗╔═╗╦  ╦╦╔═╗ ┬ ┬┌┬┐┬                           #
#    ║ ╠╦╝╠═╣╚╗╔╝║╚═╗ └┬┘││││                           #
#  o ╩ ╩╚═╩ ╩ ╚╝ ╩╚═╝o ┴ ┴ ┴┴─┘                         #
#                                                       #
# This file configures Travis CI.                       #
# (i.e. how we run the tests... mainly)                 #
#                                                       #
# https://docs.travis-ci.com/user/customizing-the-build #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

language: node_js

node_js:
  - "10"
  - "12"
  - "14"
  - "16"

branches:
  only:
    - master

notifications:
  email:
    - ci@sailsjs.com


# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   ╔═╗╦ ╦╔═╗╔╦╗╔═╗╔╦╗┬┌─┐┌─┐┌┬┐┬┌─┐┌┐┌┌─┐              #
#   ║  ║ ║╚═╗ ║ ║ ║║║║│┌─┘├─┤ │ ││ ││││└─┐              #
#   ╚═╝╚═╝╚═╝ ╩ ╚═╝╩ ╩┴└─┘┴ ┴ ┴ ┴└─┘┘└┘└─┘              #
#                                                       #
# Custom stuff specific to this package:                #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

sudo: false

services:
  - mysql2
env:
  - DB_USER=mp DB_PASS='mp'

before_script:
  - mysql2 -e 'create database mppg;'
  - mysql2 -e "create user 'mp'@'localhost' identified by 'mp';"
  - mysql2 -e "grant all privileges on * . * to 'mp'@'localhost';" -u root
  - mysql2 -e "flush privileges;" -u root
